---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa01
  namespace: canary
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment01
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
