---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  progressive-delivery-cr
rules:
  - apiGroups: [""]
    resources: ["users", "groups"] 
    verbs: [ "impersonate" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "flagger.app" ]
    resources: [ "*" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "apps" ]
    resources: [ "*" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "autoscaling" ]
    resources: [ "*" ]
    verbs: [ "get", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  progressive-delivery-crb
subjects:
  - kind: ServiceAccount
    name: progressive-delivery-sa
    namespace: flux-system
roleRef:
  kind: ClusterRole
  name: progressive-delivery-cr
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  progressive-delivery-admin-crb
subjects:
- kind: User
  name: pd-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: progressive-delivery-cr
  apiGroup: rbac.authorization.k8s.io
