on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  

name: PR CI Workflow
jobs:
  ci-go:
    name: CI Test Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup | Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.20.x
      - run: make dependencies
      - run: go mod download
      - run: make test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup | Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.20.x
      - name: Lint
        run: |
          make lint
